version: 2
registries:
  maven-github-roamingthings:
    type: maven-repository
    url: https://maven.pkg.github.com/roamingthings/*
    username: octocat
    password: ${{secrets.GHEC_PACKAGES_TOKEN}}
  maven-github-hypoport:
    type: maven-repository
    url: https://maven.pkg.github.com/hypoport/*
    username: octocat
    password: ${{secrets.GHEC_PACKAGES_TOKEN}}
updates:
  - package-ecosystem: "maven"
    registries:
      - maven-github-roamingthings
      - maven-github-hypoport
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
