quarkus.package.jar.type=legacy-jar
quarkus.mcp.server.http.streamable.dummy-init=true
quarkus.lambda-http.enable-security=true

# Logging Configuration
quarkus.log.level=${AWS_LAMBDA_LOG_LEVEL:INFO}
